use shockwave_core::geometry::Vec3;
use shockwave_path::{LayerToolpaths, ToolpathRole};

#[derive(Clone, Copy, Debug)]
pub struct MarlinConfig {
    pub filament_diameter_mm: f64,
    pub travel_feedrate_mm_min: f64,
    pub print_feedrate_mm_min: f64,
    pub coordinate_offset: Vec3,
}

impl Default for MarlinConfig {
    fn default() -> Self {
        Self {
            filament_diameter_mm: 1.75,
            travel_feedrate_mm_min: 9_000.0,
            print_feedrate_mm_min: 1_800.0,
            coordinate_offset: Vec3 {
                x: 0.0,
                y: 0.0,
                z: 0.0,
            },
        }
    }
}

pub fn write_marlin_gcode(
    layers: &[LayerToolpaths],
    config: MarlinConfig,
) -> Result<String, String> {
    if config.filament_diameter_mm <= 0.0 {
        return Err("filament diameter must be positive".to_string());
    }

    let filament_area = std::f64::consts::PI * (config.filament_diameter_mm * 0.5).powi(2);
    let mut extrusion_mm = 0.0;
    let mut output = String::new();
    output.push_str("; generated by shockwave-layers\n");
    output.push_str("G21 ; millimeters\n");
    output.push_str("G90 ; absolute coordinates\n");
    output.push_str("M82 ; absolute extrusion\n");
    output.push_str("M190 S60 ; set bed temperature and wait for it to be reached\n");
    output.push_str("G28 ; home all axes\n");
    output.push_str("G1 Z5 F5000 ; lift nozzle\n");
    output.push_str("M109 S215 ; Nozzle temperature\n");
    output.push_str("M106 ; Turn on fan\n");
    output.push('\n');
    output.push_str("; extrude a small amount of waste material\n");
    output.push_str("G92 E0\n");
    output.push_str("G1 E20 F200\n");
    output.push_str("G92 E0\n");

    for (layer_index, layer) in layers.iter().enumerate() {
        output.push_str(";LAYER_CHANGE\n");
        output.push_str(&format!(";LAYER:{layer_index}\n"));
        output.push_str(&format!("; layer field_value={:.6}\n", layer.field_value));
        let mut current_role = None;
        let mut current_position: Option<Vec3> = None;
        let travel_z = layer_travel_z(layer, config.coordinate_offset);
        for path_index in ordered_path_indices(layer) {
            let path = &layer.paths[path_index];
            if path.points.is_empty() {
                continue;
            }

            let first = offset_position(path.points[0].position, config.coordinate_offset);
            if let Some(current) = current_position
                && path.role != ToolpathRole::Travel
            {
                if current_role != Some(ToolpathRole::Travel) {
                    output.push_str(";TYPE:Travel\n");
                    current_role = Some(ToolpathRole::Travel);
                }
                output.push_str(&format!(
                    "G0 X{:.5} Y{:.5} Z{:.5} F{:.0}\n",
                    current.x, current.y, travel_z, config.travel_feedrate_mm_min
                ));
                output.push_str(&format!(
                    "G0 X{:.5} Y{:.5} Z{:.5} F{:.0}\n",
                    first.x, first.y, travel_z, config.travel_feedrate_mm_min
                ));
            }

            if current_role != Some(path.role) {
                output.push_str(&format!(";TYPE:{}\n", role_name(path.role)));
                current_role = Some(path.role);
            }

            output.push_str(&format!(
                "G0 X{:.5} Y{:.5} Z{:.5} F{:.0}\n",
                first.x, first.y, first.z, config.travel_feedrate_mm_min
            ));

            if path.role == ToolpathRole::Travel {
                current_position = Some(first);
                continue;
            }

            for segment in path.points.windows(2) {
                let a = segment[0];
                let b = segment[1];
                let position = offset_position(b.position, config.coordinate_offset);
                extrusion_mm += segment_extrusion_mm(a, b, filament_area);
                output.push_str(&format!(
                    "G1 X{:.5} Y{:.5} Z{:.5} E{:.6} F{:.0}\n",
                    position.x, position.y, position.z, extrusion_mm, config.print_feedrate_mm_min
                ));
                current_position = Some(position);
            }

            if path.closed && path.points.len() > 2 {
                let a = *path.points.last().unwrap();
                let b = path.points[0];
                let position = offset_position(b.position, config.coordinate_offset);
                extrusion_mm += segment_extrusion_mm(a, b, filament_area);
                output.push_str(&format!(
                    "G1 X{:.5} Y{:.5} Z{:.5} E{:.6} F{:.0}\n",
                    position.x, position.y, position.z, extrusion_mm, config.print_feedrate_mm_min
                ));
                current_position = Some(position);
            }
        }
    }

    output.push_str("; end of shockwave-layers gcode\n");
    Ok(output)
}

fn ordered_path_indices(layer: &LayerToolpaths) -> Vec<usize> {
    let perimeter_indices: Vec<usize> = layer
        .paths
        .iter()
        .enumerate()
        .filter(|(_, path)| path.role == ToolpathRole::Perimeter && !path.points.is_empty())
        .map(|(index, _)| index)
        .collect();
    let mut remaining: Vec<usize> = (0..layer.paths.len())
        .filter(|index| {
            layer.paths[*index].role != ToolpathRole::Perimeter
                && !layer.paths[*index].points.is_empty()
        })
        .collect();
    let mut ordered = Vec::with_capacity(remaining.len());
    let mut current = perimeter_indices
        .last()
        .map(|index| path_end_position(&layer.paths[*index]));
    ordered.extend(perimeter_indices);

    while !remaining.is_empty() {
        let next_remaining_index = if let Some(current_position) = current {
            remaining
                .iter()
                .enumerate()
                .min_by(|(_, a), (_, b)| {
                    let distance_a =
                        distance_sq(current_position, layer.paths[**a].points[0].position);
                    let distance_b =
                        distance_sq(current_position, layer.paths[**b].points[0].position);
                    distance_a.total_cmp(&distance_b)
                })
                .map(|(index, _)| index)
                .unwrap_or(0)
        } else {
            0
        };
        let path_index = remaining.swap_remove(next_remaining_index);
        current = Some(path_end_position(&layer.paths[path_index]));
        ordered.push(path_index);
    }

    ordered
}

fn path_end_position(path: &shockwave_path::Toolpath) -> Vec3 {
    if path.closed {
        path.points[0].position
    } else {
        path.points.last().unwrap().position
    }
}

fn layer_travel_z(layer: &LayerToolpaths, offset: Vec3) -> f64 {
    layer
        .paths
        .iter()
        .flat_map(|path| path.points.iter())
        .map(|point| point.position.z + offset.z)
        .fold(0.0, f64::max)
}

fn distance_sq(a: Vec3, b: Vec3) -> f64 {
    let dx = b.x - a.x;
    let dy = b.y - a.y;
    let dz = b.z - a.z;
    dx * dx + dy * dy + dz * dz
}

pub fn zero_based_coordinate_offset(layers: &[LayerToolpaths]) -> Vec3 {
    let mut min = Vec3 {
        x: f64::INFINITY,
        y: f64::INFINITY,
        z: f64::INFINITY,
    };

    for layer in layers {
        for path in &layer.paths {
            for point in &path.points {
                min.x = min.x.min(point.position.x);
                min.y = min.y.min(point.position.y);
                min.z = min.z.min(point.position.z);
            }
        }
    }

    if min.x.is_finite() {
        Vec3 {
            x: -min.x,
            y: -min.y,
            z: -min.z,
        }
    } else {
        Vec3 {
            x: 0.0,
            y: 0.0,
            z: 0.0,
        }
    }
}

fn offset_position(position: Vec3, offset: Vec3) -> Vec3 {
    Vec3 {
        x: position.x + offset.x,
        y: position.y + offset.y,
        z: position.z + offset.z,
    }
}

fn role_name(role: ToolpathRole) -> &'static str {
    match role {
        ToolpathRole::Perimeter => "Perimeter",
        ToolpathRole::Infill => "Infill",
        ToolpathRole::Travel => "Travel",
    }
}

fn segment_extrusion_mm(
    a: shockwave_path::PathPoint,
    b: shockwave_path::PathPoint,
    filament_area_mm2: f64,
) -> f64 {
    let dx = b.position.x - a.position.x;
    let dy = b.position.y - a.position.y;
    let dz = b.position.z - a.position.z;
    let length = (dx * dx + dy * dy + dz * dz).sqrt();
    let width = (a.extrusion_width_mm + b.extrusion_width_mm) * 0.5;
    let height = (a.layer_height_mm + b.layer_height_mm) * 0.5;
    length * width * height / filament_area_mm2
}

#[cfg(test)]
mod tests {
    use shockwave_core::geometry::Vec3;
    use shockwave_path::{LayerToolpaths, PathPoint, Toolpath, ToolpathRole};

    use super::*;

    #[test]
    fn writes_basic_marlin_extrusion_move() {
        let path = Toolpath {
            points: vec![
                PathPoint {
                    position: Vec3 {
                        x: 0.0,
                        y: 0.0,
                        z: 0.2,
                    },
                    extrusion_width_mm: 0.4,
                    layer_height_mm: 0.2,
                },
                PathPoint {
                    position: Vec3 {
                        x: 10.0,
                        y: 0.0,
                        z: 0.2,
                    },
                    extrusion_width_mm: 0.4,
                    layer_height_mm: 0.2,
                },
            ],
            role: ToolpathRole::Perimeter,
            closed: false,
        };
        let gcode = write_marlin_gcode(
            &[LayerToolpaths {
                field_value: 1.0,
                paths: vec![path],
            }],
            MarlinConfig::default(),
        )
        .unwrap();

        assert!(gcode.contains("G21"));
        assert!(gcode.contains("M190 S60 ; set bed temperature and wait for it to be reached"));
        assert!(gcode.contains("G28 ; home all axes"));
        assert!(gcode.contains("G1 Z5 F5000 ; lift nozzle"));
        assert!(gcode.contains("M109 S215 ; Nozzle temperature"));
        assert!(gcode.contains("G1 E20 F200"));
        assert!(gcode.contains("G1 X10.00000 Y0.00000 Z0.20000 E"));
        assert!(gcode.contains(";LAYER_CHANGE"));
        assert!(gcode.contains(";TYPE:Perimeter"));
        assert!(gcode.contains("; end of shockwave-layers gcode"));
    }

    #[test]
    fn applies_coordinate_offset_to_make_minimum_z_zero() {
        let layer = LayerToolpaths {
            field_value: 1.0,
            paths: vec![Toolpath {
                points: vec![PathPoint {
                    position: Vec3 {
                        x: -2.0,
                        y: 3.0,
                        z: -0.5,
                    },
                    extrusion_width_mm: 0.4,
                    layer_height_mm: 0.2,
                }],
                role: ToolpathRole::Travel,
                closed: false,
            }],
        };

        let offset = zero_based_coordinate_offset(std::slice::from_ref(&layer));
        assert_eq!(offset.x, 2.0);
        assert_eq!(offset.y, -3.0);
        assert_eq!(offset.z, 0.5);

        let gcode = write_marlin_gcode(
            &[layer],
            MarlinConfig {
                coordinate_offset: offset,
                ..Default::default()
            },
        )
        .unwrap();
        assert!(gcode.contains("G0 X0.00000 Y0.00000 Z0.00000"));
    }

    #[test]
    fn travels_between_paths_at_highest_layer_point() {
        let layer = LayerToolpaths {
            field_value: 1.0,
            paths: vec![
                Toolpath {
                    points: vec![
                        PathPoint {
                            position: Vec3 {
                                x: 0.0,
                                y: 0.0,
                                z: 0.2,
                            },
                            extrusion_width_mm: 0.4,
                            layer_height_mm: 0.2,
                        },
                        PathPoint {
                            position: Vec3 {
                                x: 1.0,
                                y: 0.0,
                                z: 0.2,
                            },
                            extrusion_width_mm: 0.4,
                            layer_height_mm: 0.2,
                        },
                    ],
                    role: ToolpathRole::Perimeter,
                    closed: false,
                },
                Toolpath {
                    points: vec![
                        PathPoint {
                            position: Vec3 {
                                x: 10.0,
                                y: 0.0,
                                z: 0.8,
                            },
                            extrusion_width_mm: 0.4,
                            layer_height_mm: 0.2,
                        },
                        PathPoint {
                            position: Vec3 {
                                x: 11.0,
                                y: 0.0,
                                z: 0.8,
                            },
                            extrusion_width_mm: 0.4,
                            layer_height_mm: 0.2,
                        },
                    ],
                    role: ToolpathRole::Perimeter,
                    closed: false,
                },
            ],
        };

        let gcode = write_marlin_gcode(&[layer], MarlinConfig::default()).unwrap();

        assert!(gcode.contains(";TYPE:Travel"));
        assert!(gcode.contains("G0 X1.00000 Y0.00000 Z0.80000"));
        assert!(gcode.contains("G0 X10.00000 Y0.00000 Z0.80000"));
    }

    #[test]
    fn preserves_perimeter_order_before_other_paths() {
        let point = |x| PathPoint {
            position: Vec3 { x, y: 0.0, z: 0.0 },
            extrusion_width_mm: 0.4,
            layer_height_mm: 0.2,
        };
        let layer = LayerToolpaths {
            field_value: 1.0,
            paths: vec![
                Toolpath {
                    points: vec![point(10.0), point(11.0)],
                    role: ToolpathRole::Perimeter,
                    closed: false,
                },
                Toolpath {
                    points: vec![point(0.0), point(1.0)],
                    role: ToolpathRole::Infill,
                    closed: false,
                },
                Toolpath {
                    points: vec![point(20.0), point(21.0)],
                    role: ToolpathRole::Perimeter,
                    closed: false,
                },
            ],
        };

        assert_eq!(ordered_path_indices(&layer), vec![0, 2, 1]);
    }

    #[test]
    fn rejects_invalid_filament_diameter() {
        let error = write_marlin_gcode(
            &[],
            MarlinConfig {
                filament_diameter_mm: 0.0,
                ..Default::default()
            },
        )
        .unwrap_err();

        assert!(error.contains("filament diameter"));
    }
}
